import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import "./global.scss";
export const metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
